HeapPage is done, but test does not pass. Buildfile: /home/darkangle/course_work/cs186/project1/build.xml
compile:
    [javac] Compiling 1 source file to /home/darkangle/course_work/cs186/project1/bin/src

testcompile:

runtest:
    [junit] Running simpledb.HeapPageReadTest
    [junit] Testsuite: simpledb.HeapPageReadTest
    [junit] Tests run: 4, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 0.142 sec
    [junit] Tests run: 4, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 0.142 sec
    [junit] ------------- Standard Output ---------------
    [junit] ID is []
    [junit] ID is []
    [junit] ID is []
    [junit] ID is []
    [junit] ------------- ---------------- ---------------
    [junit]
    [junit] Testcase: getId took 0.073 sec
    [junit] Testcase: getSlot took 0.013 sec
    [junit] 	Caused an ERROR
    [junit] null
    [junit] java.lang.AssertionError
    [junit] 	at simpledb.HeapPageReadTest.getSlot(HeapPageReadTest.java:117)
    [junit]
    [junit] Testcase: getNumEmptySlots took 0.005 sec
    [junit] 	Caused an ERROR
    [junit] expected:<484> but was:<0>
    [junit] java.lang.AssertionError: expected:<484> but was:<0>
    [junit] 	at simpledb.HeapPageReadTest.getNumEmptySlots(HeapPageReadTest.java:107)
    [junit]
    [junit] Testcase: testIterator took 0.005 sec
    [junit] 	Caused an ERROR
    [junit] null
    [junit] java.lang.NullPointerException
    [junit] 	at simpledb.HeapPageReadTest.testIterator(HeapPageReadTest.java:93)
    [junit]